name: Sync to ACR
on:
  push:
    paths: ['images.txt']
  workflow_dispatch:   # 手动触发
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Install skopeo
        run: sudo apt-get update && sudo apt-get install -y skopeo
      - name: Sync images
        run: |
          while read -r img; do
            [ -z "$img" ] && continue
            echo ">>> syncing $img"
            skopeo copy docker://$img \
              docker://${{ secrets.ACR_REGISTRY }}/shanhy/${img#*/}
          done < images.txt
