name: Incremental sync to ACR
on:
  push:
    paths: ['images.txt']
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.ACR_REGISTRY }}
  NAMESPACE: shanhy   # 改成你的命名空间

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Install skopeo
        run: sudo apt-get update && sudo apt-get install -y skopeo

      - name: Incremental sync
        run: |
          while read -r src; do
            [ -z "$src" ] && continue
            dst="${REGISTRY}/${NAMESPACE}/${src#*/}"  # 目标镜像
            echo ">>> 检查 ${dst} …"
            # 查询远端是否存在该 tag
            if skopeo inspect --retry-times=3 "docker://${dst}" >/dev/null 2>&1; then
              echo "  已存在，跳过"
            else
              echo "  不存在，开始同步"
              skopeo copy --retry-times=3 \
                docker://${src} \
                docker://${dst}
            fi
          done < images.txt
